var fps = 60;
var enemySpawnTimer = 25;
var spawnLocX = 10, spawnLocY = 1 * titleHeigth;
var sprite = "garen.gif";
var gameOverPNG = "gameOver";
var worldWidth = 20;
var worldHeight = 7;
var titleWidth = 64;    
var titleHeigth = 64;
var speed = 6;
var rateofFire = 10;
var towerDmg = 5;
var enemyHealth = 30;
var towerSprite = "tower.png";
var towerRange = 100;